(*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT-0
 *)

(* ========================================================================= *)
(* Phase 11 public-facing correctness theorems for                           *)
(* aes_gcm_enc_kernel_aes128.                                                *)
(*                                                                           *)
(* This file is a thin wrapper around theorems proved in                      *)
(* arm/proofs/aes_gcm_enc_kernel.ml. It exists so that:                       *)
(*                                                                           *)
(*   (a) the s2n-bignum Makefile has a single proof file to drive            *)
(*       building proofs/aes_gcm_enc_kernel_aes128.native against            *)
(*       arm/aes-gcm/aes_gcm_enc_kernel_aes128.o (the AES-128 fork .o);      *)
(*                                                                           *)
(*   (b) arm/proofs/specifications.txt has named theorems to register in     *)
(*       count-proofs.sh's spec table. NOTE: collect-specs.sh collects ONLY  *)
(*       names matching the literal `_SUBROUTINE_CORRECT` (or                 *)
(*       `_SUBROUTINE_SAFE`) substring, so a registered public theorem MUST  *)
(*       carry a name ending in `_SUBROUTINE_CORRECT`.                       *)
(*                                                                           *)
(* ========================================================================= *)
(* SCOPE OF THE PUBLIC THEOREMS (updated session 321, 2026-06-27).           *)
(*                                                                           *)
(* There are TWO public re-exports here:                                      *)
(*                                                                           *)
(* 1. AES_GCM_ENC_KERNEL_AES128_SUBROUTINE_CORRECT  (control-flow; original  *)
(*    s133 re-export of AES_GCM_ENC_KERNEL_SUBROUTINE_CORRECT). It proves:    *)
(*      - the kernel terminates and returns to its caller                     *)
(*        (`read PC s = returnaddress`),                                      *)
(*      - the kernel writes only within its declared memory frame             *)
(*        (the MAYCHANGE bytes ranges over cptr / cptr_tail / xiptr /         *)
(*        ivec_ptr+12 / the 128-byte stack scratch),                          *)
(*      - the kernel preserves all callee-saved GPRs and Q-register          *)
(*        low-halves per the AAPCS64 ABI                                      *)
(*        (`MAYCHANGE_REGS_AND_FLAGS_PERMITTED_BY_ABI`).                       *)
(*    On its own this theorem does NOT pin the ciphertext or GHASH tag.       *)
(*                                                                           *)
(* 2. AES_GCM_ENC_KERNEL_AES128_FUNCTIONAL_SUBROUTINE_CORRECT  (FUNCTIONAL;   *)
(*    session 321; re-export of the C6b theorem                              *)
(*    AES_GCM_ENC_KERNEL_BYTE_LEN_LE_64_OR_64_TO_128_OR_GT_128_SUBROUTINE_    *)
(*    CTS_COLLAPSED_MEM_CORRECT in aes_gcm_enc_kernel.ml). In addition to the *)
(*    control-flow guarantees above, it pins — over the full 3-way           *)
(*    byte-length disjunction (1<=v<=64) \/ (64<v<=128) \/ (128<v):           *)
(*      - the WHOLE-INPUT ciphertext to the in-tree FIPS-197 spec, via        *)
(*        `byte_list_at (aes_gcm_ct_bytes pt_in (word_bytereverse ctr0) ks N) *)
(*           cptr (word_ushr bit_len 3) s`                                    *)
(*        where aes_gcm_ct_bytes builds on aes_gcm_ct_block_at / aes128_cipher*)
(*        (common/fips197.ml);                                                *)
(*      - the GHASH tag in Xi memory to                                       *)
(*        `word_bytereverse (nist_ghash h (word_bytereverse initial_tag)      *)
(*           [...])` (common/ghash_nist_bridge.ml / polyval_ghash.ml);        *)
(*      - the ivec+12 counter cell, with ctr0 preserved.                      *)
(*    This is the C6b functional-fidelity contract (whole-input ciphertext    *)
(*    pinning, chosen over the C6a band-guarded/first-4-blocks contract).     *)
(*                                                                           *)
(* CARRIED SCOPE-GAPS (documented antecedents / project-scope boundaries —   *)
(* NOT soundness gaps; surfaced here, not buried):                           *)
(*   - Window-derivability (CALLER OBLIGATION). The functional theorem's PRE  *)
(*     carries `LENGTH pt_in = 64`, a windowed `pt_half` invariant, and 8     *)
(*     `aes_gcm_block_at pt_in <idx> = word_bytereverse(...)` bt-facts: the   *)
(*     wider-band ciphertext is pinned THROUGH these symbolic plaintext       *)
(*     facts, not from a single clean `byte_list_at pt_in` PRE. A higher-     *)
(*     level wrapper could derive them (deferred; needs human direction).     *)
(*   - Distinct-buffer / non-in-place (debt 6). ~40 `nonoverlapping` clauses  *)
(*     incl. ptr0 vs cptr; aws-lc may encrypt in-place.                       *)
(*   - kernel != full GCM (debt 7). No AAD GHASH, no length block, no final   *)
(*     `word_xor (aes128_cipher j0 ks) tag` — those live in aws-lc C glue     *)
(*     (gcm.c), not this assembly.                                            *)
(*   - AES-128-only, encrypt-only — per the project scope cut (Goal/Strategy);*)
(*     AES-192/256 + decrypt are deferred to follow-on work.                  *)
(* ========================================================================= *)

(* Load the standard ARM proof preamble FIRST. The aes_gcm needs-closure pulls *)
(* in common/aes.ml and common/misc.ml (via the fips197 / ghash branches), but *)
(* those files assume base.ml's preamble is already present: aes.ml uses       *)
(* WORD_RED_CONV / WORD_JOIN_CONV (Library/words.ml) and misc.ml uses SPEC1_TAC *)
(* (common/for_hollight.ml), yet neither declares the dependency. base.ml loads *)
(* Library/words.ml, common/for_hollight.ml and common/misc.ml in the right     *)
(* order (base.ml:22/31/33), so requiring it here resolves all of them at once. *)
(* The cold/interpreted gate already loads base.ml first, so this is a no-op    *)
(* there (everything "already loaded"); it only matters for the standalone      *)
(* .native build-proof.sh entry, which otherwise has no base preamble. This is  *)
(* the canonical idiom: 325 ARM proof files (incl. the sibling                  *)
(* arm/proofs/utils/aes_xts_common.ml) declare `needs "arm/proofs/base.ml"`.    *)
needs "arm/proofs/base.ml";;
needs "arm/proofs/aes_gcm_enc_kernel.ml";;

(* ------------------------------------------------------------------------- *)
(* AES_GCM_ENC_KERNEL_AES128_SUBROUTINE_CORRECT — public re-export of the     *)
(* control-flow theorem AES_GCM_ENC_KERNEL_SUBROUTINE_CORRECT.                *)
(*                                                                           *)
(* This name matches the .o file basename                                    *)
(* `arm/aes-gcm/aes_gcm_enc_kernel_aes128.o`, which is what the Makefile's   *)
(* default %.native rule (proofs/<basename>.ml) expects.                     *)
(*                                                                           *)
(* Because of the indirection between the .o basename                        *)
(* (`aes_gcm_enc_kernel_aes128`) and the existing proof file basename        *)
(* (`aes_gcm_enc_kernel`), the Makefile has an explicit rule that points    *)
(* `aes_gcm_enc_kernel_aes128.native` at this file. Retained additively so   *)
(* the original registered name keeps resolving.                            *)
(* ------------------------------------------------------------------------- *)

let AES_GCM_ENC_KERNEL_AES128_SUBROUTINE_CORRECT =
  AES_GCM_ENC_KERNEL_SUBROUTINE_CORRECT;;

(* ------------------------------------------------------------------------- *)
(* AES_GCM_ENC_KERNEL_AES128_FUNCTIONAL_SUBROUTINE_CORRECT — public re-export *)
(* of the C6b functional theorem: the whole-input ciphertext and the GHASH   *)
(* tag are pinned to the in-tree FIPS-197 / NIST-GHASH spec across all three  *)
(* byte-length bands (see scope comment above).                              *)
(*                                                                           *)
(* The name ends in `_SUBROUTINE_CORRECT` so collect-specs.sh /              *)
(* count-proofs.sh register and verify it; the underlying theorem's own name  *)
(* ends in `_SUBROUTINE_CTS_COLLAPSED_MEM_CORRECT`, which that collector      *)
(* regex would NOT pick up.                                                   *)
(* ------------------------------------------------------------------------- *)

let AES_GCM_ENC_KERNEL_AES128_FUNCTIONAL_SUBROUTINE_CORRECT =
  AES_GCM_ENC_KERNEL_BYTE_LEN_LE_64_OR_64_TO_128_OR_GT_128_SUBROUTINE_CTS_COLLAPSED_MEM_CORRECT;;

(* ------------------------------------------------------------------------- *)
(* AES_GCM_ENC_KERNEL_AES128_FUNCTIONAL_GEN_SUBROUTINE_CORRECT — public       *)
(* re-export of the Option-1 spine-generalized ("_GEN") functional theorem    *)
(* AES_GCM_ENC_KERNEL_BYTE_LEN_LE_64_OR_64_TO_128_OR_GT_128_SUBROUTINE_       *)
(* CTS_COLLAPSED_MEM_GEN_CORRECT (the 3-way merge _GEN in                      *)
(* aes_gcm_enc_kernel.ml, committed session 340).                             *)
(*                                                                           *)
(* This is the STRONGER, non-vacuous companion to the =64 functional export   *)
(* above. It carries `LENGTH pt_in = val byte_len_w` (the TRUE input length,   *)
(* not the fixed `= 64`), so the pinned whole-input ciphertext                 *)
(*   `byte_list_at (aes_gcm_ct_bytes pt_in (word_bytereverse ctr0) ks N)      *)
(*      cptr (word_ushr bit_len 3) s`                                          *)
(* is over the REAL plaintext across the full 3-way byte-length disjunction,   *)
(* removing the =64-scope zero-tail near-vacuity that the s324 well-posedness  *)
(* study surfaced for the (64,128] and >128 bands (see the =64 export's        *)
(* window-derivability note below). The =64 export is retained additively so   *)
(* no downstream consumer of the original name breaks.                         *)
(*                                                                           *)
(* Proof status: all 3 band arms (LE_64 / 64_TO_128 / GT_128 SUBROUTINE_CTS_  *)
(* COLLAPSED[_MEM]_GEN_CORRECT) are 0-hyp fragment-cold-green; the 3-way merge *)
(* is 0-hyp fragment-cold-green @k96fcf600 (merge=0 widthweaken=0).           *)
(*                                                                           *)
(* Name ends in `_SUBROUTINE_CORRECT` for the collect-specs.sh /              *)
(* count-proofs.sh regex (as with the =64 export).                            *)
(* ------------------------------------------------------------------------- *)

let AES_GCM_ENC_KERNEL_AES128_FUNCTIONAL_GEN_SUBROUTINE_CORRECT =
  AES_GCM_ENC_KERNEL_BYTE_LEN_LE_64_OR_64_TO_128_OR_GT_128_SUBROUTINE_CTS_COLLAPSED_MEM_GEN_CORRECT;;

(* ------------------------------------------------------------------------- *)
(* AES_GCM_ENC_KERNEL_AES128_FUNCTIONAL_GEN_CLEAN_SUBROUTINE_CORRECT — the    *)
(* PREFERRED, XTS-shaped public functional theorem (session 345).            *)
(*                                                                           *)
(* Same PRE as the _GEN export above (byte-identical — no weakening of the    *)
(* caller obligation), but its POST is collapsed from the merge theorem's     *)
(* ~600-line 3-way byte-length band split (each band further split into       *)
(* per-16-byte sub-bands) down to a single, readable pair:                    *)
(*                                                                           *)
(*   byte_list_at (aes_gcm_ct_bytes pt_in (word_bytereverse ctr0) ks          *)
(*                  (aes_gcm_num_blocks (val byte_len_w))) cptr byte_len_w s   *)
(*   /\                                                                       *)
(*   read (memory :> bytes128 xiptr) s =                                      *)
(*     word_bytereverse (nist_ghash h (word_bytereverse initial_tag)          *)
(*        (list_of_seq (aes_gcm_ct_block_at pt_in (word_bytereverse ctr0) ks) *)
(*                     (aes_gcm_num_blocks (val byte_len_w))))                 *)
(*                                                                           *)
(* i.e. ONE whole-input ciphertext window + ONE flat GHASH tag over the       *)
(* real number of blocks, matching the shape of AES_XTS_ENCRYPT_SUBROUTINE_   *)
(* CORRECT.  Derived purely by MP-ing the _GEN merge theorem through the      *)
(* s343/s344 collapse lemmas CT_BANDS_COLLAPSE_{LE,64_128,GT_128} — no        *)
(* symbolic re-execution, no re-proof (see aes_gcm_enc_kernel.ml, s345).      *)
(* The ivec+12 keystream counter (an internal detail, not part of the         *)
(* ciphertext/tag contract) is dropped from this POST.                        *)
(*                                                                           *)
(* Name ends in `_SUBROUTINE_CORRECT` for the collect-specs.sh /              *)
(* count-proofs.sh regex.                                                     *)
(* ------------------------------------------------------------------------- *)

let AES_GCM_ENC_KERNEL_AES128_FUNCTIONAL_GEN_CLEAN_SUBROUTINE_CORRECT =
  AES_GCM_ENC_KERNEL_AES128_FUNCTIONAL_GEN_CLEAN_SUBROUTINE_CORRECT;;

(* ------------------------------------------------------------------------- *)
(* AES_GCM_ENC_KERNEL_AES128_FUNCTIONAL_GEN_CLEAN2_SUBROUTINE_CORRECT — the   *)
(* PREFERRED, XTS-shaped public functional theorem (session 346).            *)
(*                                                                           *)
(* Identical POST and MAYCHANGE to the _CLEAN_ export above (verified aconv), *)
(* but its PRECONDITION is brought closer to XTS shape by a pure presentation *)
(* layer (derived from the _CLEAN_ theorem via ENSURES_PRECONDITION_THM +     *)
(* witness instantiation — NO symbolic re-execution, NO re-proof, and NO      *)
(* weakening: the clean2 PRE provably implies the clean PRE).                 *)
(*                                                                           *)
(* Phase-A PRE cleanups (human-directed 2nd cleanup pass, session 346):       *)
(*   - the 13 flat AES-128 key-schedule memory reads are folded into the      *)
(*     single state predicate gcm_set_key_schedule;                          *)
(*   - the 3-way byte-length band disjunction                                 *)
(*       (1<=v<=64) \/ (64<v<=128) \/ (128<v)                                *)
(*     is replaced by the single equivalent bound  1 <= val byte_len_w;      *)
(*   - the two dead outer ghost vars ks and spec_block (0 occurrences in the  *)
(*     POST / MAYCHANGE) are dropped from the universally-quantified prefix   *)
(*     (51 -> 49 vars).                                                      *)
(*                                                                           *)
(* The residual PRE bloat (the ~45 flat nonoverlapping clauses and the        *)
(* symbolic plaintext-window ghost reads) is the subject of the deferred      *)
(* Phase B (PAIRWISE fold) / Phase C (plaintext-window existential hoist).    *)
(*                                                                           *)
(* Name ends in `_SUBROUTINE_CORRECT` for the collect-specs.sh /              *)
(* count-proofs.sh regex.                                                     *)
(* ------------------------------------------------------------------------- *)

let AES_GCM_ENC_KERNEL_AES128_FUNCTIONAL_GEN_CLEAN2_SUBROUTINE_CORRECT =
  AES_GCM_ENC_KERNEL_AES128_FUNCTIONAL_GEN_CLEAN2_SUBROUTINE_CORRECT;;

(* ------------------------------------------------------------------------- *)
(* AES_GCM_ENC_KERNEL_AES128_FUNCTIONAL_GEN_CLEAN3_SUBROUTINE_CORRECT — the   *)
(* MOST XTS-shaped public functional theorem to date (session 347).          *)
(*                                                                           *)
(* Identical ensures state-PRE, POST and MAYCHANGE to the _CLEAN2_ export     *)
(* above (verified aconv), but its PRECONDITION folds the nonoverlapping      *)
(* boilerplate to XTS shape by a pure presentation layer (derived from the    *)
(* _CLEAN2_ theorem by reducing the ensures conclusion to it via MATCH_MP_TAC *)
(* and discharging its flat nonoverlapping antecedent — NO symbolic           *)
(* re-execution, NO re-proof, and NO weakening: the clean3 PRE provably       *)
(* implies the clean2 PRE by construction).                                   *)
(*                                                                           *)
(* Phase-B PRE cleanup (human-directed 2nd cleanup pass, session 347):        *)
(*   - the 45 flat nonoverlapping clauses are folded into ONE                 *)
(*       PAIRWISE nonoverlapping [8 maximal regions]                          *)
(*     (like XTS) — the cptr / ptr0 buffer widths are the true 4-block-tail   *)
(*     extent A + 64, A = val(word_and (word_sub byte_len_w 1) 0xFF..C0) —    *)
(*     plus 5 residual intra-cptr adjacency facts (two sub-regions of the     *)
(*     SAME cptr output buffer, which PAIRWISE-over-maximal cannot express).  *)
(*     Net: ~45 nonoverlapping lines -> 6.                                    *)
(*                                                                           *)
(* The residual PRE bloat (the symbolic plaintext-window ghost reads) is the  *)
(* subject of the deferred Phase C (plaintext-window existential hoist, which *)
(* carries an intrinsic 16*num_blocks block-rounded caller obligation).       *)
(*                                                                           *)
(* Name ends in `_SUBROUTINE_CORRECT` for the collect-specs.sh /              *)
(* count-proofs.sh regex.                                                     *)
(* ------------------------------------------------------------------------- *)

let AES_GCM_ENC_KERNEL_AES128_FUNCTIONAL_GEN_CLEAN3_SUBROUTINE_CORRECT =
  AES_GCM_ENC_KERNEL_AES128_FUNCTIONAL_GEN_CLEAN3_SUBROUTINE_CORRECT;;

(* ------------------------------------------------------------------------- *)
(* Caller-obligation summary (forwarded from SUBROUTINE_CORRECT's PRE).      *)
(*                                                                           *)
(* Callers must establish, in addition to the standard arg-passing and       *)
(* memory-loading preconditions, the following nonoverlapping clauses        *)
(* (added in session 131/132 to make the SUBROUTINE wrapper close):          *)
(*                                                                           *)
(*   nonoverlapping (cptr, 64) (word_sub stackpointer (word 128), 128)       *)
(*   nonoverlapping (word_add cptr (word 64), <full-blocks-tail>)            *)
(*                  (word_sub stackpointer (word 128), 128)                  *)
(*   nonoverlapping (cptr_tail, 64) (word_sub stackpointer (word 128), 128)  *)
(*   nonoverlapping (xiptr, 16) (word_sub stackpointer (word 128), 128)      *)
(*   nonoverlapping (word_add ivec_ptr (word 12), 4)                         *)
(*                  (word_sub stackpointer (word 128), 128)                  *)
(*                                                                           *)
(* These are the "5 added stack-vs-data" obligations referenced in the      *)
(* session-132 summary.                                                      *)
(* ------------------------------------------------------------------------- *)

(* ========================================================================= *)
(* AES_GCM_ENC_KERNEL_AES128_FUNCTIONAL_GEN_FIXED_SUBROUTINE_CORRECT —        *)
(* THE PREFERRED public functional export (session 350).                     *)
(*                                                                           *)
(* This is the LE-band-vacuity-REPAIRED functional theorem and should be     *)
(* preferred by callers over the _CLEAN3_/_CLEAN2_/_CLEAN_/_GEN_ exports     *)
(* above.  Session 349 proved (0-hyp) that all of merge / _GEN /             *)
(* CLEAN{,2,3} are VACUOUS in the LE band (1 <= byte_len <= 64) for nonzero  *)
(* plaintext: their band-merged PRE aliases the tail "first-blocks" reads    *)
(* bt0..3 onto the head reads b0..3 (in the LE band the DIV-64 mask is 0, so *)
(* ptr0_tail = ptr0) and pins the padding blocks to zero, forcing the whole  *)
(* <=64-byte plaintext to zero — so those exports do NOT actually verify the *)
(* kernel's ct/tag output for nonzero 1..64-byte inputs.  (Wider bands were  *)
(* always sound.)                                                            *)
(*                                                                           *)
(* The FIXED theorem is a genuine 3-way band split that repairs this:        *)
(*   - LE band  (1 <= val byte_len_w <= 64): PRE re-based on the CLEAN,       *)
(*     NON-VACUOUS LE-body theorem (b0..b3 raw reads + a byte_list_at input   *)
(*     window at the TRUE byte_len width + the four head block-facts, with    *)
(*     NO aliasing bt*/ptr0_tail reads) — nonzero <=64B plaintexts ARE        *)
(*     admitted; see the companion witness lemma                             *)
(*     AES_GCM_ENC_KERNEL_FIXED_LE_ARM_PRE_NONVACUOUS.                        *)
(*   - wider band (64 < val byte_len_w): CLEAN3's PRE (sound there).          *)
(* The POST is the flat XTS-shaped shape (one aes_gcm_ct_bytes ciphertext     *)
(* window + one flat nist_ghash tag), identical across both bands.           *)
(*                                                                           *)
(* Name ends in `_SUBROUTINE_CORRECT` for the collect-specs.sh /             *)
(* count-proofs.sh regex.                                                     *)
(* ------------------------------------------------------------------------- *)

let AES_GCM_ENC_KERNEL_AES128_FUNCTIONAL_GEN_FIXED_SUBROUTINE_CORRECT =
  AES_GCM_ENC_KERNEL_AES128_FUNCTIONAL_GEN_FIXED_SUBROUTINE_CORRECT;;
