(*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT-0
 *)

(* ========================================================================= *)
(* Phase 11 public-facing correctness theorems for                           *)
(* aes_gcm_enc_kernel_aes128.                                                *)
(*                                                                           *)
(* This file is a thin wrapper around theorems proved in                      *)
(* arm/proofs/aes_gcm_enc_kernel.ml. It exists so that:                       *)
(*                                                                           *)
(*   (a) the s2n-bignum Makefile has a single proof file to drive            *)
(*       building proofs/aes_gcm_enc_kernel_aes128.native against            *)
(*       arm/aes-gcm/aes_gcm_enc_kernel_aes128.o (the AES-128 fork .o);      *)
(*                                                                           *)
(*   (b) arm/proofs/specifications.txt has named theorems to register in     *)
(*       count-proofs.sh's spec table. NOTE: collect-specs.sh collects ONLY  *)
(*       names matching the literal `_SUBROUTINE_CORRECT` (or                 *)
(*       `_SUBROUTINE_SAFE`) substring, so a registered public theorem MUST  *)
(*       carry a name ending in `_SUBROUTINE_CORRECT`.                       *)
(*                                                                           *)
(* ========================================================================= *)
(* SCOPE OF THE PUBLIC THEOREMS (updated session 321, 2026-06-27).           *)
(*                                                                           *)
(* There are TWO public re-exports here:                                      *)
(*                                                                           *)
(* 1. AES_GCM_ENC_KERNEL_AES128_SUBROUTINE_CORRECT  (control-flow; original  *)
(*    s133 re-export of AES_GCM_ENC_KERNEL_SUBROUTINE_CORRECT). It proves:    *)
(*      - the kernel terminates and returns to its caller                     *)
(*        (`read PC s = returnaddress`),                                      *)
(*      - the kernel writes only within its declared memory frame             *)
(*        (the MAYCHANGE bytes ranges over cptr / cptr_tail / xiptr /         *)
(*        ivec_ptr+12 / the 128-byte stack scratch),                          *)
(*      - the kernel preserves all callee-saved GPRs and Q-register          *)
(*        low-halves per the AAPCS64 ABI                                      *)
(*        (`MAYCHANGE_REGS_AND_FLAGS_PERMITTED_BY_ABI`).                       *)
(*    On its own this theorem does NOT pin the ciphertext or GHASH tag.       *)
(*                                                                           *)
(* 2. AES_GCM_ENC_KERNEL_AES128_FUNCTIONAL_SUBROUTINE_CORRECT  (FUNCTIONAL;   *)
(*    session 321; re-export of the C6b theorem                              *)
(*    AES_GCM_ENC_KERNEL_BYTE_LEN_LE_64_OR_64_TO_128_OR_GT_128_SUBROUTINE_    *)
(*    CTS_COLLAPSED_MEM_CORRECT in aes_gcm_enc_kernel.ml). In addition to the *)
(*    control-flow guarantees above, it pins — over the full 3-way           *)
(*    byte-length disjunction (1<=v<=64) \/ (64<v<=128) \/ (128<v):           *)
(*      - the WHOLE-INPUT ciphertext to the in-tree FIPS-197 spec, via        *)
(*        `byte_list_at (aes_gcm_ct_bytes pt_in (word_bytereverse ctr0) ks N) *)
(*           cptr (word_ushr bit_len 3) s`                                    *)
(*        where aes_gcm_ct_bytes builds on aes_gcm_ct_block_at / aes128_cipher*)
(*        (common/fips197.ml);                                                *)
(*      - the GHASH tag in Xi memory to                                       *)
(*        `word_bytereverse (nist_ghash h (word_bytereverse initial_tag)      *)
(*           [...])` (common/ghash_nist_bridge.ml / polyval_ghash.ml);        *)
(*      - the ivec+12 counter cell, with ctr0 preserved.                      *)
(*    This is the C6b functional-fidelity contract (whole-input ciphertext    *)
(*    pinning, chosen over the C6a band-guarded/first-4-blocks contract).     *)
(*                                                                           *)
(* CARRIED SCOPE-GAPS (documented antecedents / project-scope boundaries —   *)
(* NOT soundness gaps; surfaced here, not buried):                           *)
(*   - Window-derivability (CALLER OBLIGATION). The functional theorem's PRE  *)
(*     carries `LENGTH pt_in = 64`, a windowed `pt_half` invariant, and 8     *)
(*     `aes_gcm_block_at pt_in <idx> = word_bytereverse(...)` bt-facts: the   *)
(*     wider-band ciphertext is pinned THROUGH these symbolic plaintext       *)
(*     facts, not from a single clean `byte_list_at pt_in` PRE. A higher-     *)
(*     level wrapper could derive them (deferred; needs human direction).     *)
(*   - Distinct-buffer / non-in-place (debt 6). ~40 `nonoverlapping` clauses  *)
(*     incl. ptr0 vs cptr; aws-lc may encrypt in-place.                       *)
(*   - kernel != full GCM (debt 7). No AAD GHASH, no length block, no final   *)
(*     `word_xor (aes128_cipher j0 ks) tag` — those live in aws-lc C glue     *)
(*     (gcm.c), not this assembly.                                            *)
(*   - AES-128-only, encrypt-only — per the project scope cut (Goal/Strategy);*)
(*     AES-192/256 + decrypt are deferred to follow-on work.                  *)
(* ========================================================================= *)

(* Load the standard ARM proof preamble FIRST. The aes_gcm needs-closure pulls *)
(* in common/aes.ml and common/misc.ml (via the fips197 / ghash branches), but *)
(* those files assume base.ml's preamble is already present: aes.ml uses       *)
(* WORD_RED_CONV / WORD_JOIN_CONV (Library/words.ml) and misc.ml uses SPEC1_TAC *)
(* (common/for_hollight.ml), yet neither declares the dependency. base.ml loads *)
(* Library/words.ml, common/for_hollight.ml and common/misc.ml in the right     *)
(* order (base.ml:22/31/33), so requiring it here resolves all of them at once. *)
(* The cold/interpreted gate already loads base.ml first, so this is a no-op    *)
(* there (everything "already loaded"); it only matters for the standalone      *)
(* .native build-proof.sh entry, which otherwise has no base preamble. This is  *)
(* the canonical idiom: 325 ARM proof files (incl. the sibling                  *)
(* arm/proofs/utils/aes_xts_common.ml) declare `needs "arm/proofs/base.ml"`.    *)
needs "arm/proofs/base.ml";;
needs "arm/proofs/aes_gcm_enc_kernel.ml";;

(* ------------------------------------------------------------------------- *)
(* AES_GCM_ENC_KERNEL_AES128_SUBROUTINE_CORRECT — public re-export of the     *)
(* control-flow theorem AES_GCM_ENC_KERNEL_SUBROUTINE_CORRECT.                *)
(*                                                                           *)
(* This name matches the .o file basename                                    *)
(* `arm/aes-gcm/aes_gcm_enc_kernel_aes128.o`, which is what the Makefile's   *)
(* default %.native rule (proofs/<basename>.ml) expects.                     *)
(*                                                                           *)
(* Because of the indirection between the .o basename                        *)
(* (`aes_gcm_enc_kernel_aes128`) and the existing proof file basename        *)
(* (`aes_gcm_enc_kernel`), the Makefile has an explicit rule that points    *)
(* `aes_gcm_enc_kernel_aes128.native` at this file. Retained additively so   *)
(* the original registered name keeps resolving.                            *)
(* ------------------------------------------------------------------------- *)

let AES_GCM_ENC_KERNEL_AES128_SUBROUTINE_CORRECT =
  AES_GCM_ENC_KERNEL_SUBROUTINE_CORRECT;;

(* ------------------------------------------------------------------------- *)
(* AES_GCM_ENC_KERNEL_AES128_FUNCTIONAL_SUBROUTINE_CORRECT — public re-export *)
(* of the C6b functional theorem: the whole-input ciphertext and the GHASH   *)
(* tag are pinned to the in-tree FIPS-197 / NIST-GHASH spec across all three  *)
(* byte-length bands (see scope comment above).                              *)
(*                                                                           *)
(* The name ends in `_SUBROUTINE_CORRECT` so collect-specs.sh /              *)
(* count-proofs.sh register and verify it; the underlying theorem's own name  *)
(* ends in `_SUBROUTINE_CTS_COLLAPSED_MEM_CORRECT`, which that collector      *)
(* regex would NOT pick up.                                                   *)
(* ------------------------------------------------------------------------- *)

let AES_GCM_ENC_KERNEL_AES128_FUNCTIONAL_SUBROUTINE_CORRECT =
  AES_GCM_ENC_KERNEL_BYTE_LEN_LE_64_OR_64_TO_128_OR_GT_128_SUBROUTINE_CTS_COLLAPSED_MEM_CORRECT;;

(* ------------------------------------------------------------------------- *)
(* Caller-obligation summary (forwarded from SUBROUTINE_CORRECT's PRE).      *)
(*                                                                           *)
(* Callers must establish, in addition to the standard arg-passing and       *)
(* memory-loading preconditions, the following nonoverlapping clauses        *)
(* (added in session 131/132 to make the SUBROUTINE wrapper close):          *)
(*                                                                           *)
(*   nonoverlapping (cptr, 64) (word_sub stackpointer (word 128), 128)       *)
(*   nonoverlapping (word_add cptr (word 64), <full-blocks-tail>)            *)
(*                  (word_sub stackpointer (word 128), 128)                  *)
(*   nonoverlapping (cptr_tail, 64) (word_sub stackpointer (word 128), 128)  *)
(*   nonoverlapping (xiptr, 16) (word_sub stackpointer (word 128), 128)      *)
(*   nonoverlapping (word_add ivec_ptr (word 12), 4)                         *)
(*                  (word_sub stackpointer (word 128), 128)                  *)
(*                                                                           *)
(* These are the "5 added stack-vs-data" obligations referenced in the      *)
(* session-132 summary.                                                      *)
(* ------------------------------------------------------------------------- *)
