(*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT-0
 *)

(* ========================================================================= *)
(* Minimal 1-instruction AES correctness proof.                              *)
(*                                                                           *)
(* Validates that `AESENC_FIPS197_BRIDGE` (Milestone 1 of the AES-GCM x86    *)
(* plan) fires correctly when `vaesenc` appears in a symbolically simulated  *)
(* x86 state.  The function is:                                              *)
(*                                                                           *)
(*     aes_one_round:                                                       *)
(*         vaesenc %xmm1, %xmm0, %xmm0   # xmm0 := aesenc(xmm0, xmm1)        *)
(*         ret                                                               *)
(*                                                                           *)
(* We prove that at exit the low 128 bits of XMM0 equal `fips197_round` of   *)
(* the byte-reversed inputs — the reference FIPS 197 operation on the       *)
(* NIST-orientation state.                                                   *)
(*                                                                           *)
(* Per `agent-guide.md` workflow (AES-GCM plan §5 Milestone 2), this tiny    *)
(* proof exists solely to catch stepper-context bugs that are invisible at   *)
(* the theorem level.  Single `X86_STEPS_TAC` step time: ~0.034s on the     *)
(* s2n-x86-aes checkpoint (matches the bench probe in                       *)
(* `x86/aes-gcm/README.md`).                                                 *)
(* ========================================================================= *)

needs "x86/proofs/base.ml";;
needs "x86/proofs/utils/aes_fips197_bridge.ml";;

(* The 1-instruction body plus RET.  Byte sequence generated by the GNU     *)
(* assembler from `vaesenc %xmm1, %xmm0, %xmm0; ret`.                        *)

let aes_one_round_mc = define_assert_word_list "aes_one_round_mc"
  `[word 0xc4; word 0xe2; word 0x79; word 0xdc; word 0xc1; word 0xc3]:byte list`
  [0xc4; 0xe2; 0x79; 0xdc; 0xc1; 0xc3];;

let AES_ONE_ROUND_EXEC = X86_MK_CORE_EXEC_RULE aes_one_round_mc;;

(* ------------------------------------------------------------------------- *)
(* Correctness.                                                              *)
(*                                                                           *)
(* Note: `MAYCHANGE [YMM0]` would be semantically correct here (the          *)
(* instruction zeroes YMM0's upper 128 bits and writes the result to its    *)
(* low 128 bits) but `SUBSUMED_MAYCHANGE_TAC` cannot canonicalise derived    *)
(* components like `YMM0 = ZMM0 :> zerotop_256` inside the MAYCHANGE list,  *)
(* so we state the frame in terms of the base component `ZMM0`.  Upstream   *)
(* code (mldsa_ntt.ml, mlkem_basemul_k2.ml) uses the same ZMM convention.   *)
(* ------------------------------------------------------------------------- *)

let AES_ONE_ROUND_CORRECT = prove
 (`!a k pc.
      ensures x86
        (\s. bytes_loaded s (word pc) (BUTLAST aes_one_round_mc) /\
             read RIP s = word pc /\
             read XMM0 s = a /\
             read XMM1 s = k)
        (\s. read RIP s = word(pc + 0x5) /\
             read XMM0 s = word_reversefields 8
               (fips197_round (word_reversefields 8 a)
                              (word_reversefields 8 k)))
        (MAYCHANGE [RIP] ,, MAYCHANGE [ZMM0] ,, MAYCHANGE [events])`,
  MAP_EVERY X_GEN_TAC [`a:int128`; `k:int128`; `pc:num`] THEN
  ENSURES_INIT_TAC "s0" THEN
  RULE_ASSUM_TAC(REWRITE_RULE[XMM0; XMM1; READ_ZEROTOP_128]) THEN
  X86_STEPS_TAC AES_ONE_ROUND_EXEC [1] THEN
  ENSURES_FINAL_STATE_TAC THEN
  REWRITE_TAC[XMM0; READ_ZEROTOP_128] THEN
  ASM_REWRITE_TAC[AESENC_FIPS197_BRIDGE_ALT] THEN
  CONV_TAC WORD_BLAST);;
