#!/usr/bin/env python3
"""Generate the 84 nonoverlap clauses for M8 outer CORRECT statement."""

# Fixed (per-loop-invariant) readables: k0..k10, h0,h1,h3,h4,h6,h7, red, plus,
#   sp32, sp48, sp64, sp80, sp96, sp112.  25 entries.
# iptr is handled with a single span clause (16 * 6 * iter_count) — derives
#   per-iter per-block (iptr+96i+16j, 16) via NONOVERLAPPING_SUBREGIONS.
fixed_readables = [
    ("k0",  "word_add kptr (word 18446744073709551488), 16"),
    ("k1",  "word_add kptr (word 18446744073709551504), 16"),
    ("k2",  "word_add kptr (word 18446744073709551520), 16"),
    ("k3",  "word_add kptr (word 18446744073709551536), 16"),
    ("k4",  "word_add kptr (word 18446744073709551552), 16"),
    ("k5",  "word_add kptr (word 18446744073709551568), 16"),
    ("k6",  "word_add kptr (word 18446744073709551584), 16"),
    ("k7",  "word_add kptr (word 18446744073709551600), 16"),
    ("k8",  "kptr, 16"),
    ("k9",  "word_add kptr (word 16), 16"),
    ("k10", "word_add kptr (word 32), 16"),
    ("h0",  "word_add hptr (word 18446744073709551584), 16"),
    ("h1",  "word_add hptr (word 18446744073709551600), 16"),
    ("h3",  "word_add hptr (word 16), 16"),
    ("h4",  "word_add hptr (word 32), 16"),
    ("h6",  "word_add hptr (word 64), 16"),
    ("h7",  "word_add hptr (word 80), 16"),
    ("red", "word_add cptr (word 16), 16"),
    ("plus", "word_add cptr (word 32), 16"),
    ("sp32","word_add sptr (word 32), 16"),
    ("sp48","word_add sptr (word 48), 16"),
    ("sp64","word_add sptr (word 64), 16"),
    ("sp80","word_add sptr (word 80), 16"),
    ("sp96","word_add sptr (word 96), 16"),
    ("sp112","word_add sptr (word 112), 16"),
]

# Writables (stores from M7's body, plus loop-plumbing state).
# optr span covers the 6 ciphertext blocks per iter across all iters.
writables = [
    ("optr_span", "optr, 16 * 6 * iter_count"),
    ("cbptr",     "(cbptr:int64), 16"),
    ("sp16",      "word_add sptr (word 16), 16"),
]

# iptr span (the readable that contains all per-iter plaintext blocks).
iptr_span = "iptr, 16 * 6 * iter_count"

clauses = []

# Group 1: code × writable (3 clauses)
for (wl, w) in writables:
    clauses.append(("code-vs-writable", wl,
                    f"nonoverlapping (word pc:int64,LENGTH aesni_gcm_stitched_6x_loop_mc) ({w})"))

# Group 2: writable × iptr_span (3 clauses)
for (wl, w) in writables:
    clauses.append(("writable-vs-iptr", wl,
                    f"nonoverlapping ({w}) ({iptr_span})"))

# Group 3: writable × each fixed readable (3 × 25 = 75 clauses)
for (wl, w) in writables:
    for (rl, r) in fixed_readables:
        clauses.append((f"writable-vs-{rl}", wl,
                        f"nonoverlapping ({w}) ({r})"))

# Group 4: writable × writable (3 clauses)
for i in range(len(writables)):
    for j in range(i+1, len(writables)):
        clauses.append(("writable-pair", writables[i][0] + "/" + writables[j][0],
                        f"nonoverlapping ({writables[i][1]}) ({writables[j][1]})"))

total = len(clauses)
print(f"(* {total} pairwise nonoverlap clauses, generated by tools/gen_m8_nonoverlap.py *)")
for idx, (cat, lbl, ln) in enumerate(clauses):
    suffix = " /\\" if idx < total - 1 else ""
    print(f"      {ln}{suffix}")
